name: Python_GitHub_Actions_training
on:
  push:
    branches:
      - main
      - temporary
  workflow_dispatch:  
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Fill in the db.
        run: |
          python db.py -a

      - name: Build application
        run: python app.py --host localhost --port 5000 &
        shell: bash

      - name: Test application
        run: echo "Tests to be added"
    
