name: Python_GitHub_Actions_training
on:
  push:
    branches:
      - main
      - temporary
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Fill in the db.
        run: |
          python db.py -a

      - name: Build application
        run: python app.py --host localhost --port 5000 &
        shell: bash

      - name: Test application
        run: echo "Tests to be added"
        
      - name: Update code in "temporary" branch
        run: |
          git checkout -b temporary
          git add .
          git commit -m "Update code in temporary branch"
          git push origin temporary

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update code in "temporary" branch
          body: |
            This PR updates the code in the "temporary" branch.
          branch: temporary
